name: Build Maven Project,Create Docker Image and  Push Docker Image to Docker Hub

on:
  push:
    branches: [ master ]
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
        
    - name: Build with Maven
      run: mvn clean install
      
    - name: Build Docker Image and Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
       username: ${{ secrets.DOCKER_HUB_USERNAME }}
       password: ${{ secrets.DOCKER_HUB_PASSWORD }}
       repository: 14271832/spring-boot-hello-world
       tags: ${{github.run_number}}
